package vista;

import controlador.GastoControler;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Vista de gasto
 * @author frami
 */
public class VistaGasto extends javax.swing.JFrame {

    GastoControler gastoControler = new GastoControler();

    /**
     * Creates new form VistaGasto
     */
    public VistaGasto() {
        initComponents();
        txtId.setEnabled(false);
        GastoControler.cargarTablaGastosTR(tblGasto);
        try {
            GastoControler.cargarComboProveedor(cmbProveedor);
            GastoControler.cargarComboConcepto(cmbConcepto);
            GastoControler.cargarComboServicio(cmbServicio);
            GastoControler.cargarComboLiquidacion(cmbLiquidacion);
        } catch (InterruptedException | ExecutionException | IOException ex) {
            Logger.getLogger(VistaGasto.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Ventana para la gestión de gastos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jFechaRegistro = new com.toedter.calendar.JDateChooser();
        txtModificar = new javax.swing.JButton();
        txtAlta = new javax.swing.JButton();
        txtLimpiar = new javax.swing.JButton();
        txtBaja = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGasto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroComprobante = new javax.swing.JTextField();
        jFechaPago = new com.toedter.calendar.JDateChooser();
        cmbProveedor = new javax.swing.JComboBox<>();
        cmbConcepto = new javax.swing.JComboBox<>();
        cmbServicio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbLiquidacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtModificar.setText("MODIFICAR");
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });

        txtAlta.setText("CREAR");
        txtAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltaActionPerformed(evt);
            }
        });

        txtLimpiar.setText("LIMPIAR");
        txtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimpiarActionPerformed(evt);
            }
        });

        txtBaja.setText("ELIMINAR");
        txtBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBajaActionPerformed(evt);
            }
        });

        tblGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGastoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGasto);

        jLabel2.setText("Id:");

        jLabel3.setText("Fecha registro:");

        jLabel4.setText("Concepto:");

        jLabel6.setText("Proveedor:");

        jLabel7.setText("Fecha pago:");

        jLabel8.setText("Importe:");

        jLabel10.setText("Número comprobante:");

        jLabel5.setText("Servicio:");

        jLabel9.setText("Liquidación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(2, 2, 2)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBaja)
                        .addGap(68, 68, 68)
                        .addComponent(txtModificar)
                        .addGap(84, 84, 84)
                        .addComponent(txtLimpiar)
                        .addGap(69, 69, 69))
                    .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbConcepto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLiquidacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)
                                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6))
                        .addComponent(jFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtNumeroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jFechaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlta)
                    .addComponent(txtBaja)
                    .addComponent(txtModificar)
                    .addComponent(txtLimpiar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltaActionPerformed
        /*
        Capturamos los valores
         */

        double importe = Double.parseDouble(txtImporte.getText());
        Date fechaRegistro = jFechaRegistro.getDate();
        Date fechaPago = jFechaPago.getDate();
        String numeroComprobante = txtNumeroComprobante.getText().trim();
        String proveedor = cmbProveedor.getSelectedItem().toString();
        String concepto = cmbConcepto.getSelectedItem().toString();
        String servicio = cmbServicio.getSelectedItem().toString();
        String liquidacion = cmbLiquidacion.getSelectedItem().toString();
        /*
        Guardamos los valores utilzando el controlador
         */
        gastoControler.guardarGasto(importe, fechaRegistro, fechaPago, 
                numeroComprobante, proveedor, concepto, servicio, liquidacion);
    }//GEN-LAST:event_txtAltaActionPerformed

    private void txtBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBajaActionPerformed
        String idDoc = txtId.getText().trim();
        gastoControler.eliminarGasto(idDoc);
    }//GEN-LAST:event_txtBajaActionPerformed

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        String idDoc = txtId.getText().trim();
        double importe = Double.parseDouble(txtImporte.getText());
        Date fechaRegistro = jFechaRegistro.getDate();
        Date fechaPago = jFechaPago.getDate();
        String numeroComprobante = txtNumeroComprobante.getText().trim();
        String proveedor = cmbProveedor.getSelectedItem().toString();
        String concepto = cmbConcepto.getSelectedItem().toString();
        String servicio = cmbServicio.getSelectedItem().toString();
        String liquidacion = cmbLiquidacion.getSelectedItem().toString();

        gastoControler.actualizarGasto(idDoc, importe, fechaRegistro, fechaPago, 
                numeroComprobante, proveedor, concepto, servicio, liquidacion);
    }//GEN-LAST:event_txtModificarActionPerformed

    private void txtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimpiarActionPerformed
        gastoControler.limpiarCampos(txtImporte, txtNumeroComprobante, jFechaRegistro, 
                jFechaPago, cmbProveedor, 
                cmbServicio, cmbConcepto, cmbLiquidacion);
    }//GEN-LAST:event_txtLimpiarActionPerformed

    private void tblGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGastoMouseClicked
        int selection = tblGasto.getSelectedRow();
        txtId.setText(tblGasto.getValueAt(selection, 0) + "");
        txtImporte.setText(tblGasto.getValueAt(selection, 1) + "");
        String fechaGastoString = (String) tblGasto.getValueAt(selection, 2);
        String fechaPagoString = (String) tblGasto.getValueAt(selection, 3);
        txtNumeroComprobante.setText(tblGasto.getValueAt(selection, 4) + "");
        
        // Obtener el valor de la celda de la tabla como String

// Definir el formato de fecha que se está utilizando en la tabla
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        try {
            // Convertir el String a un objeto Date utilizando el formato definido
            Date fechaGasto = dateFormat.parse(fechaGastoString);
            Date fechaPago = dateFormat.parse(fechaPagoString);

            // Establecer la fecha en el JDateChooser
            jFechaRegistro.setDate(fechaGasto);
            jFechaPago.setDate(fechaPago);
        } catch (ParseException ex) {
            // Manejar el error en caso de que el String no se pueda convertir a Date
            System.out.println("Error al convertir fecha: " + ex.getMessage());
        }

    }//GEN-LAST:event_tblGastoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new VistaGasto().setVisible(true);

            }
        });
    }

    public JTable getTblGasto() {
        return tblGasto;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtImporteGasto() {
        return txtImporte;
    }

    public JTextField getTxtNombre() {
        return txtNumeroComprobante;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbConcepto;
    private javax.swing.JComboBox<String> cmbLiquidacion;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbServicio;
    public static com.toedter.calendar.JDateChooser jFechaPago;
    public static com.toedter.calendar.JDateChooser jFechaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGasto;
    private javax.swing.JButton txtAlta;
    private javax.swing.JButton txtBaja;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JButton txtLimpiar;
    private javax.swing.JButton txtModificar;
    private javax.swing.JTextField txtNumeroComprobante;
    // End of variables declaration//GEN-END:variables

}
